# Generated by Django 6.0.3 on 2026-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_par_sac', models.DecimalField(decimal_places=2, default=1000.0, help_text="Prix de vente d'un sac de semoule en DA", max_digits=10)),
                ('devise', models.CharField(default='usd', editable=False, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prix Global',
                'verbose_name_plural': 'Prix Global',
            },
        ),
    ]
